# Generated by Django 4.0 on 2022-01-21 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='id',
        ),
        migrations.AlterField(
            model_name='friends',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.user'),
        ),
    ]
