# Generated by Django 4.0 on 2022-01-21 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_friends_id_alter_friends_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friendID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendID', to='main.user'),
        ),
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('userID', 'friendID')},
        ),
    ]
