# Generated by Django 4.0 on 2021-12-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('ID диалога', models.AutoField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('ID сообщения', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('Текст сообщения', models.CharField(max_length=1000)),
                ('Дата и время сообщения', models.DateTimeField()),
                ('dialogID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dialog')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('ID регистрации', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('Логин', models.CharField(max_length=30)),
                ('Пароль', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Регистрационные данные',
                'verbose_name_plural': 'Регистрационные даннные',
            },
        ),
        migrations.CreateModel(
            name='UserFhoto',
            fields=[
                ('ID фото пользователя', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('Путь к фотографии пользователя', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Фотография пользователя',
                'verbose_name_plural': 'Фотографии пользователя',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID пользователя', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.registrationdata')),
                ('Никнейм', models.CharField(max_length=30)),
                ('Имя', models.CharField(max_length=30)),
                ('Фамилия', models.CharField(max_length=30)),
                ('Отчество', models.CharField(max_length=30)),
                ('Информация о пользователе', models.CharField(max_length=1000)),
                ('День рождения', models.DateField()),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='PhotoInMessage',
            fields=[
                ('ID фотографии в сообшениях', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('Путь к фотографии в сообщении', models.CharField(max_length=101)),
                ('messageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.message')),
            ],
            options={
                'verbose_name': 'Фотография в сообщении',
                'verbose_name_plural': 'Фотографии в сообщениях',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('ID друга', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'verbose_name': 'Друг',
                'verbose_name_plural': 'Друзья',
            },
        ),
        migrations.CreateModel(
            name='UserDialog',
            fields=[
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.user')),
                ('dialogID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dialog')),
            ],
            options={
                'verbose_name': 'Диалог и пользователь',
                'verbose_name_plural': 'Диалоги и пользователи',
            },
        ),
    ]
