# Generated by Django 4.0 on 2021-12-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='sessionKey',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='Логин',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Никнейм',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
