# Generated by Django 4.0 on 2021-12-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_registrationdata_sessionkey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ID пользователя',
            new_name='userID',
        ),
        migrations.AlterField(
            model_name='user',
            name='День рождения',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Имя',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Информация о пользователе',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Никнейм',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Отчество',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Фамилия',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
