# Generated by Django 4.0 on 2021-12-29 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_friends_friendname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfhoto',
            old_name='ID фото пользователя',
            new_name='userPhotoID',
        ),
        migrations.RemoveField(
            model_name='userfhoto',
            name='Путь к фотографии пользователя',
        ),
        migrations.AddField(
            model_name='userfhoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='userfhoto',
            name='userID',
            field=models.ForeignKey(default=1212, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
    ]
