# Generated by Django 4.0 on 2021-12-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_id фото пользователя_userfhoto_userphotoid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='dialogName',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
