# Generated by Django 4.0 on 2021-12-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_dialog_dialogname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialog',
            old_name='ID диалога',
            new_name='dialogID',
        ),
        migrations.AlterField(
            model_name='message',
            name='Дата и время сообщения',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
