# Generated by Django 4.0 on 2022-01-21 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_photoinmessage_messagephotopath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='ID друга',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='friendName',
        ),
        migrations.AddField(
            model_name='friends',
            name='friendID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='friendID', to='main.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
