# Generated by Django 4.0 on 2022-01-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_friends_id друга_remove_friends_friendname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friendID',
        ),
    ]
