# Generated by Django 4.0 on 2022-01-21 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_friends_friendid'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friendID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friendID', to='main.user'),
            preserve_default=False,
        ),
    ]
