# Generated by Django 4.0 on 2022-01-21 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_friends_friendid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friendID',
        ),
    ]
